name: "Generate HTML and PDF"
on:
  push:
    branches:
      - master
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: extractions/setup-just@v2
    - name: Build Public Resume
      run: just build
    - name: Store Public Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: resume
        path: out/
    - name: Build Private Resume
      env:
        PHONE: ${{ secrets.PHONE_NUMBER }}
      run: just build-private "$PHONE"
    - name: Store Private Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: resume-private
        path: out/
  publish:
    runs-on: ubuntu-latest
    needs: generate
    steps:
    - uses: actions/checkout@v6
    - name: Retrieve Artifacts
      uses: actions/download-artifact@v8
      with:
        name: resume
        path: out/
    - name: Stage
      run: |
        mkdir public
        cp out/resume.html public/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
    - name: Set Tag
      id: current-datetime
      run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d-%H_%M_%S%z')" >> "$GITHUB_OUTPUT"
    - name: Build Release
      shell: bash
      run: |
        gh release create ${{ steps.current-datetime.outputs.CURRENT_DATETIME }} \
        --title ${{ steps.current-datetime.outputs.CURRENT_DATETIME }} \
        --notes "" \
        out/resume.html \
        out/resume.md \
        out/resume.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
